(in-package :cl-rabbit.examples)

(defun send-batch (conn queue-name)
  (basic-publish conn 1 "amq.direct" queue-name (babel:string-to-octets "this is the message content" :encoding :utf-8)))

(defun test-send ()
  (with-connection (conn)
    (let ((socket (tcp-socket-new conn)))
      (socket-open socket "localhost" 5672)
      (login-sasl-plain conn "/" "guest" "guest")
      (channel-open conn 1)
      (send-batch conn "foo"))))

(defun recv-loop (conn)
  (maybe-release-buffers conn)
  (consume-message conn))

(defun test-recv ()
  (with-connection (conn)
    (let ((socket (tcp-socket-new conn)))
      (socket-open socket "localhost" 5672)
      (login-sasl-plain conn "/" "guest" "guest")
      (channel-open conn 1)
      (let ((queue-name (queue-declare conn 1 :auto-delete t :queue "foo")))
        (queue-bind conn 1 queue-name "amq.direct" "foo")
        (basic-consume conn 1 queue-name)
        (let ((result (recv-loop conn)))
          (format t "Got message: ~s, content: ~s" result (babel:octets-to-string (message/body (envelope/message result))
                                                                                  :encoding :utf-8)))))))
